---
# tasks for installing tmux from source

- name: Ensure the tmux_download_dir exists
  file:
    path: "{{ tmux_download_dir }}"
    state: directory

- name: download and unzip the specified tmux package
  unarchive:
    src: "https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz"
    dest: "{{ tmux_download_dir }}"
    remote_src: yes

- name: Run configure if it has not been run already
  command: "./configure"
  args:
    chdir: "{{ tmux_download_dir }}/tmux-{{ tmux_version }}"
    creates: "{{ tmux_download_dir }}/tmux-{{ tmux_version }}/Makefile"
  notify: install
