---
- name: Verify
  hosts: all
  tasks:
    - name: Get tmux version
      command: tmux -V
      register: result
      changed_when: false
    - name: Fail if version was not retrieved
      fail:
        msg: Tmux was not installed
      when: result.rc != 0
